### ISSUE TITLE
..

### ISSUE THREAD

**Issue by l3op** [Sasuke78200/GTAV_PS3_NativeCall#2]
Is this working with 1.26?? I'v tried to compile it. But nothing work :)
I added an output to debug it and it seems it's stay on GetThreadByName.. No New thread

**Comment by ToufikBenJaa** [comment]
It works only with GTA V 1.21

**Comment by l3op** [comment]
Is there any chance to make it work with 1.26?

**Comment by ToufikBenJaa** [comment]
Well, I'm sorry I won't update this I don't code for PS3 anymore

**Comment by l3op** [comment]
Thank ya
